### ISSUE TITLE
Trying to install newer version of NPK over old one

### ISSUE THREAD

**Issue by manves** [c6fc/npk#91] opened 2023-12-04 18:36 UTC
Hello,

We are attempting to update our npk instance in our aws environment since we are getting a new error when starting a campaign.
![image](https://github.com/c6fc/npk/assets/46289911/761546b0-d6a4-4c43-a025-25cc0a56bb54)
However when we run the one liner, it says we were not able to get quotas. However in our previous install, we were allotted a lot of instances in different regions. Is there a proper way to remove the npk instance and do a fresh install? Running the one liner does not seem to work.

[+] Retrieved all active regions
[-] Unable to get quotas for us-east-1, but this isn't fatal.
[-] Unable to get quotas for us-east-1, but this isn't fatal.
[-] Unable to get quotas for us-east-2, but this isn't fatal.
[-] Unable to get quotas for us-east-2, but this isn't fatal.
[-] Unable to get quotas for ca-central-1, but this isn't fatal.
[-] Unable to get quotas for ca-central-1, but this isn't fatal.
[-] Unable to get quotas for us-west-1, but this isn't fatal.
[-] Unable to get quotas for eu-west-2, but this isn't fatal.
[-] Unable to get quotas for eu-west-2, but this isn't fatal.
[-] Unable to get quotas for us-west-1, but this isn't fatal.
[-] Unable to get quotas for us-west-2, but this isn't fatal.
[-] Unable to get quotas for us-west-2, but this isn't fatal.
[-] Unable to get quotas for eu-west-1, but this isn't fatal.
[-] Unable to get quotas for eu-west-1, but this isn't fatal.
[-] Unable to get quotas for eu-west-3, but this isn't fatal.
[-] Unable to get quotas for eu-west-3, but this isn't fatal.
[-] Unable to get quotas for eu-central-1, but this isn't fatal.
[-] Unable to get quotas for eu-central-1, but this isn't fatal.
[-] Unable to get quotas for sa-east-1, but this isn't fatal.
[-] Unable to get quotas for eu-north-1, but this isn't fatal.
[-] Unable to get quotas for sa-east-1, but this isn't fatal.
[-] Unable to get quotas for eu-north-1, but this isn't fatal.
[-] Unable to get quotas for ap-northeast-3, but this isn't fatal.
[-] Unable to get quotas for ap-northeast-3, but this isn't fatal.
[-] Unable to get quotas for ap-northeast-1, but this isn't fatal.
[-] Unable to get quotas for ap-northeast-1, but this isn't fatal.
[-] Unable to get quotas for ap-south-1, but this isn't fatal.
[-] Unable to get quotas for ap-northeast-2, but this isn't fatal.
[-] Unable to get quotas for ap-northeast-2, but this isn't fatal.
[-] Unable to get quotas for ap-south-1, but this isn't fatal.
[-] Unable to get quotas for ap-southeast-2, but this isn't fatal.
[-] Unable to get quotas for ap-southeast-2, but this isn't fatal.
[-] Unable to get quotas for ap-southeast-1, but this isn't fatal.
[-] Unable to get quotas for ap-southeast-1, but this isn't fatal.
[!] You are permitted zero GPU spot instances across all types and regions.
You cannot proceed without increasing your limits.
-> A limit of at least 4 is required for minimal capacity.
-> A limit of 40 is required to use the largest instances.
[!] Unable to proceed.
[+] Terraform 1.2.5 installed successfully

**Comment by c6fc** [comment] 2023-12-08 01:01
I pushed a fix for the 'Unable to find a suitable AMI', it was caused by a breaking change by AWS on 11/15. That part should be fine now.

**Comment by manves** [comment] 2023-12-14 16:25
Thank you! I will take a look at it today with my team.

**Closed** 2023-12-19 01:37 UTC
