### ISSUE TITLE
NPK v3 Testing Bugs / Improvements

### ISSUE THREAD

**Issue by bzekanovic** [c6fc/npk#29] opened 2022-01-17 17:46 UTC
Found couple of issues below that could cause confusion.

1. Events  Campaign started date is not correct. 
![image](https://user-images.githubusercontent.com/16389468/149815699-279f3bea-96d8-4dd8-aa8b-c5245853738d.png)

2. We've noticed in one event that campaign cost was not correct. I'm not sure what caused this, but it would be great to look into if cost values on campaign and event metrics is correct. 
![image](https://user-images.githubusercontent.com/16389468/149816021-8f71f339-ee27-49e4-9b4c-6dc421941b17.png)

3. Favorite hashes settings doesn't make sense to allow multiple values since new UI only shows default hash type. 

4. It would be great to add large file upload UI to new campaign user interface. 
![image](https://user-images.githubusercontent.com/16389468/149816440-927a8956-b7bb-4abc-b4b5-803d8c1a2c25.png)

Thanks,

**Comment by c6fc** [comment] 2022-03-01 17:25
1 and 2 are fixed in dev. This was caused by the AWS spot fleet history API sometimes truncating older events before the spot fleet timed out entirely. This means that the 'instance start' events were missing, but 'instance terminated' events weren't, which made the spot_monitor calculate the price as though the instance had been running since epoch. I've added a sanity check to avoid this, but since I can't recreate it consistently, time will tell if it was an effective fix.

3 is valid, and I removed the auto-created setting.

4 I don't intend to fix, since v4 will likely see some substantial changes to how campaign files are provided.

All this is in dev, and I'll close when merged to main.

**Comment by c6fc** [comment] 2022-03-05 06:29
I retract what I said about 4. It turns out that the large upload failures from the new campaign piece were actually a bug, and not a limit. With the bug cleared, the new campaign file uploader can now handle as large of files as s3 can handle; 5 TiB. I verified it myself with a 17 GiB file, which is probably sufficient for most use-cases. Maybe someone will try larger someday.

Hoping to merge to main tomorrow once the documentation is caught up.

**Comment by c6fc** [comment] 2022-03-06 01:07
Fixed in [9265d45](https://github.com/c6fc/npk/commit/9265d454d1758ffbc5810a6ed7abb6dc19fcf57a)

**Closed by c6fc** 2022-03-06 01:07 UTC
Labels: fix pending
